//! Authentication repository: the single-admin auth config and Forms sessions.
//!
//! The auth config is a single-row JSON document (id pinned to 1), mirroring the
//! media-management store; an absent row means "open" (the zero-config default).
//! Sessions are CSPRNG tokens with a unix-seconds expiry, looked up on every
//! cookie-bearing request and deleted on logout. SECURITY: the config `body`
//! carries the password *hash* only — the plaintext is never modelled, so it can
//! never reach this layer.

use cellarr_core::AuthConfig;
use crate::dialect::{pq, DbPool};
use sqlx::Row;

use crate::error::{DbError, Result};
use crate::writer::WriterHandle;

/// A live, non-expired session: the username it authenticates and its expiry.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AuthSession {
    /// The admin username this session authenticates.
    pub username: String,
    /// Expiry as unix seconds.
    pub expires_at: i64,
}

/// Reads/writes for the auth config and the Forms session store.
#[derive(Clone)]
pub struct AuthRepo {
    pool: DbPool,
    writer: WriterHandle,
}

impl AuthRepo {
    pub(crate) fn new(pool: DbPool, writer: WriterHandle) -> Self {
        Self { pool, writer }
    }

    /// The single-admin auth configuration. Returns [`AuthConfig::open`] (the
    /// zero-config "no auth" default) when no row has been written yet, so a fresh
    /// install is usable immediately without a credential.
    ///
    /// # Errors
    /// Returns a [`DbError`] on query/decode failure.
    pub async fn get_config(&self) -> Result<AuthConfig> {
        let row = sqlx::query(&pq("SELECT body FROM auth_config WHERE id = 1"))
            .fetch_optional(&self.pool)
            .await?;
        match row {
            Some(row) => {
                let body: String = row.try_get("body")?;
                serde_json::from_str(&body).map_err(DbError::from)
            }
            None => Ok(AuthConfig::open()),
        }
    }

    /// Persist the single-admin auth configuration, replacing the one settings
    /// document in place. SECURITY: `config.password_hash` must be a hash, never a
    /// plaintext password (enforced by the type — plaintext is not a field).
    ///
    /// # Errors
    /// Returns a [`DbError`] on serialization or write failure.
    pub async fn set_config(&self, config: &AuthConfig) -> Result<()> {
        let body = serde_json::to_string(config)?;
        self.writer
            .submit(move |conn| {
                Box::pin(async move {
                    sqlx::query(&pq(
                        "INSERT INTO auth_config (id, body) VALUES (1, ?1)
                         ON CONFLICT(id) DO UPDATE SET body = excluded.body"),
                    )
                    .bind(body)
                    .execute(&mut *conn)
                    .await?;
                    Ok(())
                })
            })
            .await
    }

    /// Mint a session: store `token` for `username`, valid until `expires_at`
    /// (unix seconds). The token is generated by the caller from a CSPRNG.
    ///
    /// # Errors
    /// Returns a [`DbError`] on write failure.
    pub async fn create_session(
        &self,
        token: &str,
        username: &str,
        created_at: i64,
        expires_at: i64,
    ) -> Result<()> {
        let token = token.to_string();
        let username = username.to_string();
        self.writer
            .submit(move |conn| {
                Box::pin(async move {
                    sqlx::query(&pq(
                        "INSERT INTO auth_session (token, username, created_at, expires_at)
                         VALUES (?1, ?2, ?3, ?4)"),
                    )
                    .bind(token)
                    .bind(username)
                    .bind(created_at)
                    .bind(expires_at)
                    .execute(&mut *conn)
                    .await?;
                    Ok(())
                })
            })
            .await
    }

    /// Look up a session by token, returning it only if it exists **and** has not
    /// expired as of `now` (unix seconds). An expired or unknown token yields
    /// `None`, so the middleware treats both identically (no validity oracle).
    ///
    /// # Errors
    /// Returns a [`DbError`] on query/decode failure.
    pub async fn get_session(&self, token: &str, now: i64) -> Result<Option<AuthSession>> {
        let row = sqlx::query(&pq(
            "SELECT username, expires_at FROM auth_session
             WHERE token = ?1 AND expires_at > ?2"),
        )
        .bind(token)
        .bind(now)
        .fetch_optional(&self.pool)
        .await?;
        match row {
            Some(row) => {
                let username: String = row.try_get("username")?;
                let expires_at: i64 = row.try_get("expires_at")?;
                Ok(Some(AuthSession {
                    username,
                    expires_at,
                }))
            }
            None => Ok(None),
        }
    }

    /// Delete a session by token (logout). Idempotent: returns whether a row was
    /// removed.
    ///
    /// # Errors
    /// Returns a [`DbError`] on write failure.
    pub async fn delete_session(&self, token: &str) -> Result<bool> {
        use std::sync::atomic::{AtomicBool, Ordering};
        use std::sync::Arc;

        let token = token.to_string();
        let removed = Arc::new(AtomicBool::new(false));
        let removed_inner = Arc::clone(&removed);
        self.writer
            .submit(move |conn| {
                Box::pin(async move {
                    let result = sqlx::query(&pq("DELETE FROM auth_session WHERE token = ?1"))
                        .bind(token)
                        .execute(&mut *conn)
                        .await?;
                    removed_inner.store(result.rows_affected() > 0, Ordering::SeqCst);
                    Ok(())
                })
            })
            .await?;
        Ok(removed.load(Ordering::SeqCst))
    }

    /// Delete every session (revoke all logins). Called when the credential or the
    /// auth method changes, so stale sessions never outlive the credential that
    /// minted them.
    ///
    /// # Errors
    /// Returns a [`DbError`] on write failure.
    pub async fn delete_all_sessions(&self) -> Result<()> {
        self.writer
            .submit(move |conn| {
                Box::pin(async move {
                    sqlx::query(&pq("DELETE FROM auth_session"))
                        .execute(&mut *conn)
                        .await?;
                    Ok(())
                })
            })
            .await
    }

    /// Sweep expired sessions (a maintenance cleanup). Returns the number removed.
    ///
    /// # Errors
    /// Returns a [`DbError`] on write failure.
    pub async fn purge_expired_sessions(&self, now: i64) -> Result<u64> {
        use std::sync::atomic::{AtomicU64, Ordering};
        use std::sync::Arc;

        let removed = Arc::new(AtomicU64::new(0));
        let removed_inner = Arc::clone(&removed);
        self.writer
            .submit(move |conn| {
                Box::pin(async move {
                    let result = sqlx::query(&pq("DELETE FROM auth_session WHERE expires_at <= ?1"))
                        .bind(now)
                        .execute(&mut *conn)
                        .await?;
                    removed_inner.store(result.rows_affected(), Ordering::SeqCst);
                    Ok(())
                })
            })
            .await?;
        Ok(removed.load(Ordering::SeqCst))
    }
}
